# Generated by Django 3.2.5 on 2021-07-30 13:21

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='preview_image',
            field=models.ImageField(default='media/uploads/preview-images/default.jpg', upload_to='media/uploads/preview-images/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
