# Generated by Django 3.2.5 on 2021-07-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210730_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='preview_image',
            field=models.ImageField(default='uploads/preview-images/default.jpg', upload_to='uploads/preview-images/'),
        ),
    ]
