# Generated by Django 3.2.5 on 2021-08-01 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_publication_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='data',
        ),
    ]
